org: laredojuan25
service: api-diagrams

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::352677750379:role/LabRole
  layers:
    - arn:aws:lambda:us-east-1:764866452798:layer:graphviz:9

functions:
  crear_er:
    handler: render_er.lambda_handler
    events:
      - http:
          path: /diagrama/crear-er
          method: post
          cors: true
          integration: lambda
